services:
  lunotel-api:
    container_name: lunotel-api
    image: node:20.16.0
    restart: always

    ports:
      - '5001:3001'

    working_dir: /usr/src/lunotel
    volumes:
      - ./:/usr/src/lunotel

    networks:
      - monorepo-network

    command: sh -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  lunotel-batch:
    container_name: lunotel-batch
    image: node:20.16.0
    restart: always

    ports:
      - '5002:3002'

    working_dir: /usr/src/lunotel
    volumes:
      - ./:/usr/src/lunotel

    networks:
      - monorepo-network

    command: sh -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    external: true
