import { registerEnumType } from '@nestjs/graphql';

export enum NotificationType {
	RESERVATION_CREATED_USER = 'RESERVATION_CREATED_USER',
	RESERVATION_CREATED_HOST = 'RESERVATION_CREATED_HOST',
	RESERVATION_UPDATED_USER = 'RESERVATION_UPDATED_USER',
	RESERVATION_UPDATED_HOST = 'RESERVATION_UPDATED_HOST',
	RESERVATION_CANCELED_USER = 'RESERVATION_CANCELED_USER',
	RESERVATION_CANCELED_HOST = 'RESERVATION_CANCELED_HOST',
}

registerEnumType(NotificationType, { name: 'NotificationType' });
