import { registerEnumType } from '@nestjs/graphql';

export enum RoomStatus {
	AVAILABLE = 'AVAILABLE',
	UNAVAILABLE = 'UNAVAILABLE',
	OCCUPIED = 'OCCUPIED',
	CLEANING = 'CLEANING',
	MAINTENANCE = 'MAINTENANCE',
}

registerEnumType(RoomStatus, {
	name: 'RoomStatus',
});

export enum RoomAmenity {
	FINTESS = 'FINTESS',
	RESTAURANT = 'RESTAURANT',
	SPA = 'SPA',
	WIFI = 'WIFI',
	AIR_CONDITIONER = 'AIR_CONDITIONER',
	TV = 'TV',
	MINIBAR = 'MINIBAR',
	REFRIGERATOR = 'REFRIGERATOR',
	COFFEE_MACHINE = 'COFFEE_MACHINE',
	HAIR_DRYER = 'HAIR_DRYER',
	BATHTUB = 'BATHTUB',
	SHOWER_BOOTH = 'SHOWER_BOOTH',
	MICROWAVE = 'MICROWAVE',
	WASHING_MACHINE = 'WASHING_MACHINE',
	IRON = 'IRON',
	SAFE = 'SAFE',
	BALCONY = 'BALCONY',
	BED = 'BED',
	SOFA = 'SOFA',
	DESK = 'DESK',
	WARDROBE = 'WARDROBE',
	SLIPPERS = 'SLIPPERS',
	TOWELS = 'TOWELS',
	SHAMPOO = 'SHAMPOO',
	BODY_WASH = 'BODY_WASH',
	TOOTHBRUSH = 'TOOTHBRUSH',
	TELEPHONE = 'TELEPHONE',
	CLOCK = 'CLOCK',
	BLINDS = 'BLINDS',
	AIR_PURIFIER = 'AIR_PURIFIER',
	HUMIDIFIER = 'HUMIDIFIER',
	HEATING = 'HEATING',
	NON_SMOKING = 'NON_SMOKING',
}

registerEnumType(RoomAmenity, {
	name: 'RoomAmenity',
});
