import { registerEnumType } from '@nestjs/graphql';

export enum PropertyType {
	ALL = 'ALL',
	MOTEL = 'MOTEL',
	HOTEL = 'HOTEL',
	PENSION = 'PENSION',
	POLL_VILLA = 'POLL_VILLA',
	CAMPING = 'CAMPING',
	GLAMPING = 'GLAMPING',
}
registerEnumType(PropertyType, {
	name: 'PropertyType',
});

export enum PropertyStatus {
	DRAFT = 'DRAFT',
	ACTIVE = 'ACTIVE',
	HOLD = 'HOLD',
	SOLD = 'SOLD',
	INACTIVE = 'INACTIVE',
	BLOCKED = 'BLOCKED',
	DELETE = 'DELETE',
}
registerEnumType(PropertyStatus, {
	name: 'PropertyStatus',
});

export enum PropertyLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	INCHEON = 'INCHEON',
	DAEGU = 'DAEGU',
	GYEONGJU = 'GYEONGJU',
	GWANGJU = 'GWANGJU',
	CHONJU = 'CHONJU',
	DAEJON = 'DAEJON',
	JEJU = 'JEJU',
	GANGNEUNG = 'GANGNEUNG',
	SOKCHO = 'SOKCHO',
	YEOSU = 'YEOSU',
	HEUNDE = 'HEUNDE',
	GAPYEONG = 'GAPYEONG',
}

registerEnumType(PropertyLocation, {
	name: 'PropertyLocation',
});

export enum PropertyAmenity {
	FINTESS = 'FINTESS',
	RESTAURANT = 'RESTAURANT',
	SPA = 'SPA',
	WIFI = 'WIFI',
	AIR_CONDITIONER = 'AIR_CONDITIONER',
	TV = 'TV',
	MINIBAR = 'MINIBAR',
	REFRIGERATOR = 'REFRIGERATOR',
	COFFEE_MACHINE = 'COFFEE_MACHINE',
	HAIR_DRYER = 'HAIR_DRYER',
	BATHTUB = 'BATHTUB',
	SHOWER_BOOTH = 'SHOWER_BOOTH',
	MICROWAVE = 'MICROWAVE',
	WASHING_MACHINE = 'WASHING_MACHINE',
	IRON = 'IRON',
	SAFE = 'SAFE',
	BALCONY = 'BALCONY',
	BED = 'BED',
	SOFA = 'SOFA',
	DESK = 'DESK',
	WARDROBE = 'WARDROBE',
	SLIPPERS = 'SLIPPERS',
	TOWELS = 'TOWELS',
	SHAMPOO = 'SHAMPOO',
	BODY_WASH = 'BODY_WASH',
	TOOTHBRUSH = 'TOOTHBRUSH',
	TELEPHONE = 'TELEPHONE',
	CLOCK = 'CLOCK',
	BLINDS = 'BLINDS',
	AIR_PURIFIER = 'AIR_PURIFIER',
	HUMIDIFIER = 'HUMIDIFIER',
	HEATING = 'HEATING',
	NON_SMOKING = 'NON_SMOKING',
}

registerEnumType(PropertyAmenity, {
	name: 'PropertyAmenity',
});

export enum PropertyOtherAmenity {
	BREAKFAST_PROVIDED = 'BREAKFAST_PROVIDED',
	FREE_PARKING = 'FREE_PARKING',
	PETS_ALLOWED = 'PETS_ALLOWED',
	SAUNA_JJIMJILBANG = 'SAUNA_JJIMJILBANG',
	IN_ROOM_COOKING = 'IN_ROOM_COOKING',
	PICK_UP_SERVICE = 'PICK_UP_SERVICE',
	SMOKING_ALLOWED = 'SMOKING_ALLOWED',
	LUGGAGE_STORAGE = 'LUGGAGE_STORAGE',
}

registerEnumType(PropertyOtherAmenity, {
	name: 'PropertyOtherAmenity',
});
